# Generated by Django 5.2.7 on 2026-03-25 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counseling', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='careerpath',
            old_name='description',
            new_name='desc',
        ),
    ]
