# Generated by Django 5.2.7 on 2026-04-29 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counseling', '0003_studentprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='category',
            field=models.CharField(blank=True, default='General', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='expected_marks',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='stream',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='tenth_marks',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='twelfth_marks',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
